/**
 * To avoid running "npm run eject" and remove conveniences of react-scripts
 * a script was instead created to update script paths generated by react-scripts. 
 * An additional declaration of "postbuild" was added to package.json to run this script. 
 */
const fs = require('fs');


const readFile = function (filePath){
    let data = fs.readFileSync(filePath, {encoding: "utf8", flag:"r"})
    
    data = data.replace(/href="\//g, 'href="./')
    data = data.replace(/src="\//g, 'src="./')
    return data
}
const writeFile = function(filePath, data){
    fs.writeFileSync(filePath, data)
}

const filePath = "./build/index.html"
const data = readFile(filePath)
writeFile(filePath, data)
